#!/bin/bash

input="$@"

count=1
while true; do
  ( sh -c "$input" ) 
  if [ $? -ne 0 ]; then
    echo "Restarting command, on attempt: $count"
    count=$(( $count + 1))
    sleep 1
  else
    break
  fi
done

